disableFastRender = true
theme = "roman"

[frontmatter]
date = [":filename", ":default"]

[[menu.main]]
identifier = "about"
name = "À propos"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "index"
name = "Table des matières"
url = "/"
weight = 2

[[menu.main]]
identifier = "print"
name = "Impression"
url = "/print"
weight = 3

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML"]

[permalinks]
pages = "/:filename"
posts = "/:filename"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[taxonomies]
tag = "tags"
